---

- name: Create configuration directory
  file:
    path: /etc/docker
    owner: root
    group: root
    mode: '0644'
    state: directory

- name: Copy in Docker configuration
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker
