---

- name: Include Distro specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      skip: true

- name: Add user to docker group
  user:
    name: "{{ docker_ansible_docker_user }}"
    groups: docker
    append: true
