---

- name: Install pre-requisites
  apt:
    update_cache: true
    state: present
    name:
      - curl
      - gnupg-agent
      - software-properties-common
      - ca-certificates
      - apt-transport-https

- name: Uninstall old docker packages (if present)
  apt:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
#    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    update_cache: true
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify: Restart Docker
