---

- name: Restart Docker
  block:
    - name: Reload systemctl
      systemd:
        daemon_reload: true

    - name: Make sure docker is restarted and enabled
      service:
        name: docker
        state: restarted
        enabled: true
